### ISSUE TITLE
The getter 'accentColor' isn't defined for the class 'ThemeData'

### ISSUE THREAD

**Issue by Mae623** [muhammadtalhasultan/flutter-slide-to-act#15]
Hello, I meet a question as below:
Error (Xcode): ../../../.pub-cache/hosted/pub.flutter-io.cn/slide_to_act-2.0.1/lib/slide_to_act.dart:128:59: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.

version：
Flutter (Channel master, 3.8.0-13.0.pre.103, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
Android toolchain - develop for Android devices (Android SDK version 33.0.1)

Maybe you need to upgrade it.

**Comment by juri117** [comment]
seems like the replacement is colorScheme.secondary
https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties#accentcolor

a fix is ready to be merged here: https://github.com/imtoori/flutter-slide-to-act/pull/18

**Comment by muhammadtalhasultan** [comment]
#18 is merged
